# Generated by Django 5.2 on 2025-07-15 23:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BillingRecord',
            new_name='BillingProfile',
        ),
    ]
