# Generated by Django 5.2 on 2025-07-16 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GestEmail',
            new_name='GuestEmail',
        ),
    ]
